// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	obterEstado: () => typedError<EstadoDaTela, ErroComando>(__TAURI_INVOKE("obter_estado")),
	alternarExecucao: () => typedError<EstadoDaTela, ErroComando>(__TAURI_INVOKE("alternar_execucao")),
	reiniciarEtapa: () => typedError<EstadoDaTela, ErroComando>(__TAURI_INVOKE("reiniciar_etapa")),
	/**
	 *  Alem de avancar a etapa, realinha a duracao ativa com o plano de
	 *  duracoes: em modo individual, a sessao recem-entrada pode ter uma
	 *  duracao diferente da que estava valendo antes. Ver
	 *  [`pomodoro_dominio::PlanoDoCiclo::realinhar_apos_avancar`].
	 */
	pularEtapa: () => typedError<EstadoDaTela, ErroComando>(__TAURI_INVOKE("pular_etapa")),
	alterarIniciarAutomaticamente: (valor: boolean) => typedError<EstadoDaTela, ErroComando>(__TAURI_INVOKE("alterar_iniciar_automaticamente", { valor })),
	obterPlano: () => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("obter_plano")),
	redimensionar: (novaQuantidade: number) => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("redimensionar", { novaQuantidade })),
	trocarModo: (novoModo: ModoDeDuracao) => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("trocar_modo", { novoModo })),
	alterarDuracaoGlobalFoco: (minutos: number) => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("alterar_duracao_global_foco", { minutos })),
	alterarDuracaoGlobalPausa: (minutos: number) => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("alterar_duracao_global_pausa", { minutos })),
	alterarDuracaoIndividualFoco: (numeroSessao: number, minutos: number) => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("alterar_duracao_individual_foco", { numeroSessao, minutos })),
	alterarDuracaoIndividualPausa: (numeroSessao: number, minutos: number) => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("alterar_duracao_individual_pausa", { numeroSessao, minutos })),
	alterarAtividadeGlobal: (nome: string | null, url: string | null) => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("alterar_atividade_global", { nome, url })),
	alterarAtividadeIndividual: (numeroSessao: number, nome: string | null, url: string | null) => typedError<EstadoDoPlano, ErroComandoDePlano>(__TAURI_INVOKE("alterar_atividade_individual", { numeroSessao, nome, url })),
	obterContadoresDoDia: () => typedError<EstadoDoHistorico, ErroComando>(__TAURI_INVOKE("obter_contadores_do_dia")),
	/**
	 *  Unico command exposto a janela de bloqueio (PRD §7.6) — derruba o
	 *  webview da atividade, destroi as janelas de bloqueio, restaura os
	 *  atalhos do GNOME e conta como pausa interrompida. Nao toca no timer.
	 */
	confirmarUrgencia: () => __TAURI_INVOKE<void>("confirmar_urgencia"),
	/**
	 *  Alterna mostrar/esconder a janela do widget (PRD §9) — chamado pelo
	 *  botao "Widget" no cabecalho da janela principal.
	 */
	alternarWidget: () => __TAURI_INVOKE<void>("alternar_widget"),
};

/** Events */
export const events = {
	bloqueioMudou: makeEvent<BloqueioMudou>("bloqueio-mudou"),
	estadoMudou: makeEvent<EstadoMudou>("estado-mudou"),
	historicoMudou: makeEvent<HistoricoMudou>("historico-mudou"),
	planoMudou: makeEvent<PlanoMudou>("plano-mudou"),
	tomadaDeFocoOcorreu: makeEvent<TomadaDeFocoOcorreu>("tomada-de-foco-ocorreu"),
};

/* Types */
/**
 *  Atividade de pausa (PRD §7.1): nome e URL independentemente opcionais.
 *  `rotulo` vem pronto do dominio — o React nao reimplementa a regra de
 *  fallback (nome -> hostname sem "www." -> "atividade").
 */
export type AtividadeDoPlano = {
	nome: string | null,
	url: string | null,
	rotulo: string,
};

/**  Emitido so ao entrar/sair do bloqueio (PRD §7) — nunca a 1Hz. */
export type BloqueioMudou = EstadoDoBloqueio;

export type ErroComando = "EstadoInacessivel";

export type ErroComandoDePlano = "EstadoInacessivel" | ({ QuantidadeDeSessoesInvalida: {
	recebido: number,
} }) & { DuracaoDeFocoInvalida?: never; DuracaoDePausaInvalida?: never; EsquemaDeUrlNaoPermitido?: never; SessaoForaDoPlano?: never; UrlDeAtividadeNaoEUmaUrl?: never } | ({ DuracaoDeFocoInvalida: {
	recebido: number,
} }) & { DuracaoDePausaInvalida?: never; EsquemaDeUrlNaoPermitido?: never; QuantidadeDeSessoesInvalida?: never; SessaoForaDoPlano?: never; UrlDeAtividadeNaoEUmaUrl?: never } | ({ DuracaoDePausaInvalida: {
	recebido: number,
} }) & { DuracaoDeFocoInvalida?: never; EsquemaDeUrlNaoPermitido?: never; QuantidadeDeSessoesInvalida?: never; SessaoForaDoPlano?: never; UrlDeAtividadeNaoEUmaUrl?: never } | ({ SessaoForaDoPlano: {
	recebido: number,
	total: number,
} }) & { DuracaoDeFocoInvalida?: never; DuracaoDePausaInvalida?: never; EsquemaDeUrlNaoPermitido?: never; QuantidadeDeSessoesInvalida?: never; UrlDeAtividadeNaoEUmaUrl?: never } | ({ UrlDeAtividadeNaoEUmaUrl: {
	recebido: string,
} }) & { DuracaoDeFocoInvalida?: never; DuracaoDePausaInvalida?: never; EsquemaDeUrlNaoPermitido?: never; QuantidadeDeSessoesInvalida?: never; SessaoForaDoPlano?: never } | ({ EsquemaDeUrlNaoPermitido: {
	esquema: string,
} }) & { DuracaoDeFocoInvalida?: never; DuracaoDePausaInvalida?: never; QuantidadeDeSessoesInvalida?: never; SessaoForaDoPlano?: never; UrlDeAtividadeNaoEUmaUrl?: never };

/**
 *  Retrato do ciclo num instante. O prazo e absoluto: o React deriva
 *  `mm:ss` localmente a partir dele via `requestAnimationFrame`, sem
 *  receber tick do Rust.
 */
export type EstadoDaTela = {
	etapa: Etapa,
	numeroSessao: number,
	totalSessoes: number,
	/**
	 *  `i64` forcado a `number` no TS: ms desde a epoca cabe com folga em
	 *  `Number.MAX_SAFE_INTEGER` por seculos, e o dominio ja garante >= 0.
	 */
	prazoEpocaMs: number | null,
	restanteMs: number,
	rodando: boolean,
	duracaoTotalMs: number,
	iniciarAutomaticamente: boolean,
};

/**
 *  Se o modo de bloqueio (PRD §7) esta ativo agora. Emitido so na transicao
 *  (entrada/saida), nunca a 1Hz — o React so precisa disto pra desativar os
 *  atalhos do app (M/Esc) enquanto o bloqueio segura a tela.
 */
export type EstadoDoBloqueio = {
	ativo: boolean,
};

/**
 *  Contadores do dia corrente, pro rodape da tela principal (PRD §12). Nao
 *  expoe o historico de 90 dias inteiro — Estatisticas esta fora da v1, e
 *  nada mais consome os dias passados hoje.
 */
export type EstadoDoHistorico = {
	sessoesConcluidasHoje: number,
	tempoDeFocoHojeMs: number,
};

/**
 *  Retrato do plano de duracoes: modo ativo, duracoes globais e o plano
 *  individual completo — os dois conjuntos sempre presentes, coexistindo.
 */
export type EstadoDoPlano = {
	modo: ModoDeDuracao,
	totalSessoes: number,
	duracaoGlobalFocoMs: number,
	duracaoGlobalPausaMs: number,
	atividadeGlobal: AtividadeDoPlano,
	planoIndividual: SessaoDoPlano[],
};

/**  Emitido so em transicao de estado — o Rust nunca manda tick a 1Hz. */
export type EstadoMudou = EstadoDaTela;

export type Etapa = "foco" | "pausa";

/**
 *  Emitido quando os contadores do dia mudam: sessao concluida, foco
 *  pulado pela metade ou pausa interrompida.
 */
export type HistoricoMudou = EstadoDoHistorico;

/**
 *  Modo de duracao do plano — espelho de `pomodoro_dominio::ModoDeDuracao`
 *  na fronteira Rust<->TS.
 */
export type ModoDeDuracao = "global" | "individual";

/**
 *  Emitido quando o plano de duracoes muda: redimensionamento, troca de
 *  modo ou alteracao de duracao (global ou individual).
 */
export type PlanoMudou = EstadoDoPlano;

/**  Duracoes de foco/pausa e atividade de uma sessao do plano individual. */
export type SessaoDoPlano = {
	focoMs: number,
	pausaMs: number,
	atividade: AtividadeDoPlano,
};

/**
 *  Emitido so quando a janela principal realmente é trazida pra frente
 *  (PRD §8) — nunca inferido no frontend a partir da transicao de etapa,
 *  porque isso teria que reimplementar as duas condicoes que o Rust ja
 *  decide (fim de Foco automatico, nunca skip manual; so com URL
 *  aplicavel).
 */
export type TomadaDeFocoOcorreu = null;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

